### ISSUE TITLE
version 2.1.0.BUILD-SNAPSHOT is not avaliable

### ISSUE THREAD

**Issue by I333750** [spring-cloud/spring-cloud-task#493] opened 2018-12-09 11:10 UTC
Hello, not sure if this was due to my maven repo , when i set my sample project version as :<version>2.1.0.BUILD-SNAPSHOT</version>。
The pom juts can not work.
Is there another form version that  can be used?

**Comment by cppwfs** [comment] 2018-12-10 13:55
I need more detail in order to help you.   
What does your POM look like?
Was there a stack trace?

**Comment by cppwfs** [comment] 2018-12-10 14:02
Also look at the information provided in https://github.com/spring-cloud-task-app-starters/timestamp-batch/issues/6.  That may be the cause.

**Comment by sabbyanandan** [comment] 2018-12-10 15:17
Also, @I333750, for questions like this please use StackOverflow going forward. Since there's a duplicate issue in spring-cloud-task-app-starters/timestamp-batch#6, I will close this.

**Closed by sabbyanandan** 2018-12-10 15:17 UTC
