### ISSUE TITLE
 Failed to start bean 'taskLifecycleListener'

### ISSUE THREAD

**Issue by vincent6533** [spring-cloud/spring-cloud-task#496] opened 2018-12-12 03:45 UTC
spring-boot-version:2.0.4.RELEASE
spring-cloud-task.version:2.0.0.RELEASE
mysql.version:5.1.44

The task sometimes doesn't execute.

detail:
[ERROR] 2018-12-12 05:30:03.911 [main] o.s.c.t.l.TaskLifecycleListener - An event to end a task has been received for a task that has not yet started.
[ERROR] 2018-12-12 07:30:03.864 [main] o.s.c.t.l.TaskLifecycleListener - An event to end a task has been received for a task that has not yet started.

[WARN ] 2018-12-12 04:30:05.103 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！
[WARN ] 2018-12-12 05:00:04.707 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！
[WARN ] 2018-12-12 05:30:03.909 [main] o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 87 not found
[WARN ] 2018-12-12 06:00:04.722 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！
[WARN ] 2018-12-12 06:30:04.780 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！
[WARN ] 2018-12-12 07:00:04.612 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！
[WARN ] 2018-12-12 07:30:03.862 [main] o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 91 not found
[WARN ] 2018-12-12 08:00:04.838 [main] c.l.s.i.e.tasklet.CheckTicketTasklet - FTP服务器上暂时没有待处理的tar！

**Comment by vincent6533** [comment] 2018-12-12 03:59
database record:

86	2018-12-12 05:00:04	2018-12-12 05:00:08	eticket-cpic-v101	0			2018-12-12 05:00:08	eticket-cpic-v101-14b61b63-8a24-4838-ac4b-332da5c52432	
87			eticket-cpic-v101				2018-12-12 05:30:09	eticket-cpic-v101-e6dfe9cd-96de-4e30-abef-0829911082f0	
88	2018-12-12 06:00:04	2018-12-12 06:00:06	eticket-cpic-v101	0			2018-12-12 06:00:06	eticket-cpic-v101-2936ac07-3b2a-45b6-b3cf-30938fb72b0c	
89	2018-12-12 06:30:04	2018-12-12 06:30:06	eticket-cpic-v101	0			2018-12-12 06:30:06	eticket-cpic-v101-4831d73c-c881-4732-94b2-b5f5bcd31fff	
90	2018-12-12 07:00:04	2018-12-12 07:00:06	eticket-cpic-v101	0			2018-12-12 07:00:06	eticket-cpic-v101-9229e524-dbdc-4dfc-ad82-2a9da4d92ef4	
91			eticket-cpic-v101				2018-12-12 07:30:14	eticket-cpic-v101-0d756963-a64f-4951-afdc-3964301b360c	
92	2018-12-12 08:00:04	2018-12-12 08:00:07	eticket-cpic-v101	0			2018-12-12 08:00:07	eticket-cpic-v101-a71ce7b7-a9c1-4f42-bd3f-4cfef95c1a7a	
![image](https://user-images.githubusercontent.com/16218819/49846248-4faf9a00-fe05-11e8-8240-6b4b7e2057f5.png)

**Comment by cppwfs** [comment] 2018-12-12 14:10
How are you launching your tasks?   Is it through Spring Cloud Data Flow?  If so, what version and platform of SCDF are you using.

**Comment by vincent6533** [comment] 2018-12-13 01:58
yes,it through Spring Cloud Data Flow.

SCDF version : 1.6.2.RELEASE

**Comment by cppwfs** [comment] 2018-12-13 16:34
I'm not able to reproduce using:  

* Spring Cloud Data Flow Server Local 1.6.2
* Timestamp Spring Cloud Task App using `Boot 2.0.4` and `Task 2.0.0`
* Mysql 5.7.11
* Scenario:
   * Using curl I executed the following command `curl 'http://localhost:9393/tasks/executions' -i -X POST -d "name=tsetse"` 30 times with a 5 second  sleep between each request

 Which of the following platforms of Spring Cloud Data Flow are you using? :
* Local
* Cloud Foundry
* Kubernetes

Do you have an app that you can share via github that reproduced the problem?

**Comment by vincent6533** [comment] 2018-12-14 08:57
I want to confirm that the tasks doesn't find TaskExecution ID,why database still hava ID record.
Is it written first and then read?

[WARN ] 2018-12-12 05:30:03.909 [main] o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'; nested exception is java.lang.IllegalArgumentException: Invalid TaskExecution, ID 87 not found
![image](https://user-images.githubusercontent.com/16218819/49993031-9dbccd00-ffc0-11e8-95a3-c93491199748.png)

I will send you email with app.

**Comment by cppwfs** [comment] 2018-12-14 14:17
Spring Cloud Data Flow inserts a stub `TaskExecution` prior to launching the Task itself.   Then when it launches the task it sets the `spring.cloud.task.executionId` property for the task, so that the task app will use this `executionId`.

**Comment by vincent6533** [comment] 2018-12-17 02:53
Thanks for your reminder.I found the law of this error. It looks no different in scdf's logs,but there are a few seconds delay in time compared to the normal log .They are all executed normally except 87 and 91.
I think it is caused by this reason.
![image](https://user-images.githubusercontent.com/16218819/50063426-4f3d4780-01e7-11e9-818c-85448b61abd5.png)

[INFO ] 2018-12-12 04:30:00.126 [http-nio-9393-exec-9] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=85
[INFO ] 2018-12-12 04:30:00.209 [http-nio-9393-exec-9] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-5216e344-b617-4882-9990-862e13747784
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544560200125/eticket-cpic-v101-5216e344-b617-4882-9990-862e13747784
[INFO ] 2018-12-12 05:00:00.117 [http-nio-9393-exec-5] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=86
[INFO ] 2018-12-12 05:00:00.162 [http-nio-9393-exec-5] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-14b61b63-8a24-4838-ac4b-332da5c52432
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544562000115/eticket-cpic-v101-14b61b63-8a24-4838-ac4b-332da5c52432
[INFO ] 2018-12-12 05:30:00.120 [http-nio-9393-exec-2] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=87
[INFO ] 2018-12-12 05:30:10.209 [http-nio-9393-exec-2] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-e6dfe9cd-96de-4e30-abef-0829911082f0
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544563800118/eticket-cpic-v101-e6dfe9cd-96de-4e30-abef-0829911082f0
[INFO ] 2018-12-12 06:00:00.125 [http-nio-9393-exec-8] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=88
[INFO ] 2018-12-12 06:00:00.211 [http-nio-9393-exec-8] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-2936ac07-3b2a-45b6-b3cf-30938fb72b0c
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544565600124/eticket-cpic-v101-2936ac07-3b2a-45b6-b3cf-30938fb72b0c
[INFO ] 2018-12-12 06:30:00.184 [http-nio-9393-exec-1] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=89
[INFO ] 2018-12-12 06:30:00.227 [http-nio-9393-exec-1] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-4831d73c-c881-4732-94b2-b5f5bcd31fff
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544567400183/eticket-cpic-v101-4831d73c-c881-4732-94b2-b5f5bcd31fff
[INFO ] 2018-12-12 07:00:00.071 [http-nio-9393-exec-9] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=90
[INFO ] 2018-12-12 07:00:00.155 [http-nio-9393-exec-9] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-9229e524-dbdc-4dfc-ad82-2a9da4d92ef4
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544569200069/eticket-cpic-v101-9229e524-dbdc-4dfc-ad82-2a9da4d92ef4
[INFO ] 2018-12-12 07:30:00.083 [http-nio-9393-exec-5] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=91
[INFO ] 2018-12-12 07:30:15.340 [http-nio-9393-exec-5] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-0d756963-a64f-4951-afdc-3964301b360c
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544571000081/eticket-cpic-v101-0d756963-a64f-4951-afdc-3964301b360c
[INFO ] 2018-12-12 08:00:00.073 [http-nio-9393-exec-2] o.s.c.d.spi.local.LocalTaskLauncher - Command to be executed: /home/industry/jdk1.8.0_181/jre/bin/java -jar /home/industry/batch-eticket-cpic/batch-eticket-cpic-1.0.1.jar --spring.cloud.task.executionid=92
[INFO ] 2018-12-12 08:00:00.159 [http-nio-9393-exec-2] o.s.c.d.spi.local.LocalTaskLauncher - launching task eticket-cpic-v101-a71ce7b7-a9c1-4f42-bd3f-4cfef95c1a7a
   Logs will be in /tmp/eticket-cpic-v1017062777560484158899/1544572800071/eticket-cpic-v101-a71ce7b7-a9c1-4f42-bd3f-4cfef95c1a7a

**Comment by vincent6533** [comment] 2018-12-17 03:09
I have a new problem today.The scdf doesn't work anymore. The tasks are executed once every 5 minutes.

[ERROR] 2018-12-17 10:50:00.010 [http-nio-9393-exec-10] o.s.c.d.s.c.RestControllerAdvice - Caught exception while handling a request
java.lang.IllegalStateException: The maximum concurrent task executions [20] is at its limit.
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskService.executeTask(DefaultTaskService.java:183)
	at sun.reflect.GeneratedMethodAccessor239.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy147.executeTask(Unknown Source)
	at org.springframework.cloud.dataflow.server.controller.TaskExecutionController.launch(TaskExecutionController.java:150)
	at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vincent6533** [comment] 2018-12-17 03:43
Thank you for your help.I hope you can help me solve the first problem. Thank you!

**Comment by cppwfs** [comment] 2018-12-17 21:59
As to the first problem this looks like it is a Spring Cloud Data Flow issue.   I'm closing this issue and opening a new one in SCDF located at: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2692.

**Closed by cppwfs** 2018-12-17 21:59 UTC
